<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.test.testcases.LoginTest" tests="1" time="229.118" ignored="0" failures="0" timestamp="11 Apr 2017 12:23:53 GMT" skipped="0" hostname="MdAshrafs-MacBook-Pro.local" errors="1">
  <testcase name="Check_whether_user_is_able_to_login_without_any_issues" time="229.118" classname="com.test.testcases.LoginTest">
    <error type="org.openqa.selenium.WebDriverException" message="An unknown server-side error occurred while processing the command. Original error: UiAUtomator shut down unexpectedly (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 229.11 seconds
Build info: version: &#039;2.47.1&#039;, revision: &#039;411b314&#039;, time: &#039;2015-07-30 02:56:46&#039;
System info: host: &#039;MdAshrafs-MacBook-Pro.local&#039;, ip: &#039;10.128.7.213&#039;, os.name: &#039;Mac OS X&#039;, os.arch: &#039;x86_64&#039;, os.version: &#039;10.12.4&#039;, java.version: &#039;1.8.0_111&#039;
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{app=/Users/md.ashrafiftekhar/Downloads/app-devServer-release (3).apk, appPackage=org.cscpbc.parenting, networkConnectionEnabled=true, warnings={}, bundleId=org.csbpsc.app.parenting.parenting, databaseEnabled=false, deviceName=0715f78909b62336, platform=LINUX, deviceUDID=0715f78909b62336, appActivity=org.cscpbc.parenting.view.activity.LaunchActivity, desired={app=/Users/md.ashrafiftekhar/Downloads/app-devServer-release (3).apk, appPackage=org.cscpbc.parenting, appActivity=org.cscpbc.parenting.view.activity.LaunchActivity, platformVersion=6.0.1, bundleId=org.csbpsc.app.parenting.parenting, platformName=Android, deviceName=testdevice}, platformVersion=6.0.1, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, javascriptEnabled=true, platformName=Android}]
Session ID: f7ed7ad1-69eb-41cb-99e3-129292c17119">
      <![CDATA[org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: UiAUtomator shut down unexpectedly (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 229.11 seconds
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 02:56:46'
System info: host: 'MdAshrafs-MacBook-Pro.local', ip: '10.128.7.213', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.4', java.version: '1.8.0_111'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{app=/Users/md.ashrafiftekhar/Downloads/app-devServer-release (3).apk, appPackage=org.cscpbc.parenting, networkConnectionEnabled=true, warnings={}, bundleId=org.csbpsc.app.parenting.parenting, databaseEnabled=false, deviceName=0715f78909b62336, platform=LINUX, deviceUDID=0715f78909b62336, appActivity=org.cscpbc.parenting.view.activity.LaunchActivity, desired={app=/Users/md.ashrafiftekhar/Downloads/app-devServer-release (3).apk, appPackage=org.cscpbc.parenting, appActivity=org.cscpbc.parenting.view.activity.LaunchActivity, platformVersion=6.0.1, bundleId=org.csbpsc.app.parenting.parenting, platformName=Android, deviceName=testdevice}, platformVersion=6.0.1, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, javascriptEnabled=true, platformName=Android}]
Session ID: f7ed7ad1-69eb-41cb-99e3-129292c17119
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:235)
	at org.openqa.selenium.remote.RemoteWebDriver.getPageSource(RemoteWebDriver.java:455)
	at com.test.testcases.LoginTest.Check_whether_user_is_able_to_login_without_any_issues(LoginTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- Check_whether_user_is_able_to_login_without_any_issues -->
</testsuite> <!-- com.test.testcases.LoginTest -->
