<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MdAshrafs-MacBook-Pro.local" ignored="0" name="Default test" tests="1" failures="1" timestamp="27 Mar 2017 05:09:26 GMT" time="40.711" errors="0">
  <testcase name="Check_whether_user_is_able_to_login_without_any_issues" time="19.49" classname="com.test.testcases.LoginTest">
    <failure type="java.lang.IllegalArgumentException" message="@$Proxy5: one of [Ljava.lang.String;@5ab956d7 should be filled">
      <![CDATA[java.lang.IllegalArgumentException: @$Proxy5: one of [Ljava.lang.String;@5ab956d7 should be filled
	at io.appium.java_client.pagefactory.AppiumAnnotations.getFilledValue(AppiumAnnotations.java:264)
	at io.appium.java_client.pagefactory.AppiumAnnotations.buildBy(AppiumAnnotations.java:348)
	at io.appium.java_client.pagefactory.AppiumElementLocator.<init>(AppiumElementLocator.java:109)
	at io.appium.java_client.pagefactory.AppiumElementLocatorFactory.createLocator(AppiumElementLocatorFactory.java:41)
	at io.appium.java_client.pagefactory.AppiumFieldDecorator.decorate(AppiumFieldDecorator.java:102)
	at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:112)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:104)
	at com.test.pages.HomePage.<init>(HomePage.java:14)
	at com.test.pages.LoginPage.loginResults(LoginPage.java:37)
	at com.test.testcases.LoginTest.Check_whether_user_is_able_to_login_without_any_issues(LoginTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- Check_whether_user_is_able_to_login_without_any_issues -->
</testsuite> <!-- Default test -->
